### ISSUE TITLE
Deployment eines nginx Ingress Controllers

### ISSUE THREAD

**Issue by TomHutter** [plusserver/docs#74]
helm search repo ingress-nginx
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
ingress-nginx/ingress-nginx     4.10.0          1.10.0          Ingress controller for Kubernetes using NGINX a...

Die in der Doku verwendete Chart Version ist veraltet. Am besten ganz weg lassen ;-)

**Comment by kub3anni** [comment]
@TomHutter Vielen Dank für dein Feedback, wir freuen uns sehr darüber! Wir haben einen entsprechenden Hinweis hinzugefügt :)
